### ISSUE TITLE
wrong date and time

### ISSUE THREAD

**Issue by dimm0k** [KAsp3rd/android_device_lge_pplus#3]
In TWRP the time is off by 3 hours when I have the correct time zone set, which for me is EST. Along with this, the date when creating backups is fast by about 3 days! Mentioned this in #twrp and was told that there's a patch supposedly for this, specifically a build flag to control code execution. I'm no programmer so this is a bit above my head...

**Comment by KAsp3rd** [comment]
This has been discussed in detail in the thread. Due to the way that LG has
implement their timing in the kernel it is not fixable with TWRP's build
flag. It would take more effort then I can currently dedicate to write the
functionality into TWRP to get this to work properly as it would require a
new class/function written into TWRP source.

**Comment by KAsp3rd** [comment]
This has been resolved. Please update to TWRP 3.0.0-0
